export const cards = [
    {
        id: 1,
        product: "Product 1",
        price: 100,
        company: "Company 1",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 2,
        product: "Product 2",
        price: 200,
        company: "Company 2",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 3,
        product: "Product 3",
        price: 300,
        company: "Company 3",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 4,
        product: "Product 4",
        price: 400,
        company: "Company 4",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 5,
        product: "Product 5",
        price: 500,
        compady: "Company 5",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 6,
        product: "Product 6",
        price: 600,
        company: "Company 6",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 7,
        product: "Product 7",
        price: 700,
        company: "Company 7",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 8,
        product: "Product 8",
        price: 800,
        company: "Company 8",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 9,
        product: "Product 9",
        price: 900,
        company: "Company 9",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 10,
        product: "Product 10",
        price: 1000,
        company: "Company 10",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 11,
        product: "Product 11",
        price: 1100,
        company: "Company 11",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 12,
        product: "Product 12",
        price: 1200,
        compady: "Company 12",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 13,
        product: "Product 13",
        price: 1300,
        company: "Company 13",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
    {
        id: 14,
        product: "Product 14",
        price: 1400,
        company: "Company 14",
        imageURL: 'http//:blablabla.ua',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus, dolor. Neque, nemo cum pariatur dolores sapiente incidunt nihil sit enim explicabo recusandae exercitationem culpa reprehenderit tempore, obcaecati facere nobis facilis?",
    },
]
